"""Added new columns for new features

Revision ID: 04a093ce20b9
Revises: df2cdd3924c1
Create Date: 2026-03-21 11:55:23.565824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a093ce20b9'
down_revision: Union[str, Sequence[str], None] = 'df2cdd3924c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('chat_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('embed_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('embed_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('anthropic_key_enc', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('gemini_key_enc', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('ollama_base_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ollama_base_url')
    op.drop_column('users', 'gemini_key_enc')
    op.drop_column('users', 'anthropic_key_enc')
    op.drop_column('users', 'embed_model')
    op.drop_column('users', 'embed_provider')
    op.drop_column('users', 'chat_model')
    op.drop_column('users', 'chat_provider')
    # ### end Alembic commands ###
