"""initial tables

Revision ID: 0af1f2730616
Revises: 2babb93e7784
Create Date: 2026-03-29 07:42:09.601255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af1f2730616'
down_revision: Union[str, Sequence[str], None] = '2babb93e7784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('openai_api_key_encrypted', sa.String(), nullable=True),
    sa.Column('preferred_model', sa.String(), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('chat_provider', sa.String(), nullable=True),
    sa.Column('chat_model', sa.String(), nullable=True),
    sa.Column('embed_provider', sa.String(), nullable=True),
    sa.Column('embed_model', sa.String(), nullable=True),
    sa.Column('anthropic_key_enc', sa.Text(), nullable=True),
    sa.Column('gemini_key_enc', sa.Text(), nullable=True),
    sa.Column('ollama_base_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='mnemo'
    )
    op.create_index(op.f('ix_mnemo_users_email'), 'users', ['email'], unique=True, schema='mnemo')
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['mnemo.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mnemo'
    )
    op.create_table('data_source_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('file', 'google_drive', 'sql', name='sourcetypeenum'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doc_count', sa.Integer(), nullable=True),
    sa.Column('original_bytes', sa.Integer(), nullable=True),
    sa.Column('text_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['mnemo.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mnemo'
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['mnemo.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mnemo'
    )
    op.create_table('kb_shares',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('shared_with_user_id', sa.String(), nullable=False),
    sa.Column('permission', sa.Enum('viewer', 'contributor', name='permissionenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['mnemo.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['mnemo.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mnemo'
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['mnemo.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mnemo'
    )
    op.create_index(op.f('ix_mnemo_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True, schema='mnemo')
    op.create_table('storage_usage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('original_bytes', sa.Integer(), nullable=True),
    sa.Column('text_bytes', sa.Integer(), nullable=True),
    sa.Column('last_calculated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('warning_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['mnemo.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='mnemo'
    )
    op.create_table('user_api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('requests_made', sa.Integer(), nullable=True),
    sa.Column('request_limit', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['mnemo.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mnemo'
    )
    op.create_index(op.f('ix_mnemo_user_api_keys_key_hash'), 'user_api_keys', ['key_hash'], unique=True, schema='mnemo')
    op.create_table('user_vector_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('store_type', sa.Enum('chroma', 'pgvector', 'pinecone', 'azure_search', name='vectorstoretypeenum'), nullable=True),
    sa.Column('config_encrypted', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('migration_status', sa.String(), nullable=True),
    sa.Column('migration_source', sa.String(), nullable=True),
    sa.Column('migration_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('migration_done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('migrated_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['mnemo.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='mnemo'
    )
    op.create_table('verification_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['mnemo.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mnemo'
    )
    op.create_index(op.f('ix_mnemo_verification_tokens_token'), 'verification_tokens', ['token'], unique=True, schema='mnemo')
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['mnemo.chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mnemo'
    )
    op.create_table('system_prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('scope', sa.Enum('global_', 'source', name='systempromptscopeenum'), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['mnemo.data_source_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['mnemo.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mnemo'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_prompts', schema='mnemo')
    op.drop_table('chat_messages', schema='mnemo')
    op.drop_index(op.f('ix_mnemo_verification_tokens_token'), table_name='verification_tokens', schema='mnemo')
    op.drop_table('verification_tokens', schema='mnemo')
    op.drop_table('user_vector_config', schema='mnemo')
    op.drop_index(op.f('ix_mnemo_user_api_keys_key_hash'), table_name='user_api_keys', schema='mnemo')
    op.drop_table('user_api_keys', schema='mnemo')
    op.drop_table('storage_usage', schema='mnemo')
    op.drop_index(op.f('ix_mnemo_password_reset_tokens_token'), table_name='password_reset_tokens', schema='mnemo')
    op.drop_table('password_reset_tokens', schema='mnemo')
    op.drop_table('kb_shares', schema='mnemo')
    op.drop_table('documents', schema='mnemo')
    op.drop_table('data_source_connections', schema='mnemo')
    op.drop_table('chat_sessions', schema='mnemo')
    op.drop_index(op.f('ix_mnemo_users_email'), table_name='users', schema='mnemo')
    op.drop_table('users', schema='mnemo')
    # ### end Alembic commands ###
