"""Created 4 new tables for new features

Revision ID: a1e42e9d6b68
Revises: f26ddd9b577a
Create Date: 2026-03-20 22:33:59.479890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e42e9d6b68'
down_revision: Union[str, Sequence[str], None] = 'f26ddd9b577a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
