"""add migration tracking to user_vector_config

Revision ID: df2cdd3924c1
Revises: a1e42e9d6b68
Create Date: 2026-03-20 23:54:13.206098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2cdd3924c1'
down_revision: Union[str, Sequence[str], None] = 'a1e42e9d6b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_vector_config', sa.Column('migration_status', sa.String(), nullable=True))
    op.add_column('user_vector_config', sa.Column('migration_source', sa.String(), nullable=True))
    op.add_column('user_vector_config', sa.Column('migration_started', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_vector_config', sa.Column('migration_done_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_vector_config', sa.Column('migrated_count', sa.Integer(), nullable=True))
    op.add_column('user_vector_config', sa.Column('total_count', sa.Integer(), nullable=True))
    op.add_column('user_vector_config', sa.Column('is_primary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_vector_config', 'is_primary')
    op.drop_column('user_vector_config', 'total_count')
    op.drop_column('user_vector_config', 'migrated_count')
    op.drop_column('user_vector_config', 'migration_done_at')
    op.drop_column('user_vector_config', 'migration_started')
    op.drop_column('user_vector_config', 'migration_source')
    op.drop_column('user_vector_config', 'migration_status')
    # ### end Alembic commands ###
